apiVersion: sample.zoetrope.github.io/v1
kind: MyApp
metadata:
  name: myapp-sample
spec:
  podTemplate:
    template:
      spec:
        containers:
          - name: nginx
            image: nginx:latest
            imagePullPolicy: IfNotPresent
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 3
              periodSeconds: 4
              failureThreshold: 6
  serviceTemplate: {}
